#!/bin/bash
#
# FILENAME: 10searchitems.sh
# FILEPATH: {docroot}/cgi-bin/queries/
# PARAMS  : bibid (used for logging)
#           Reads output from utils/makebiblist.sh /tmp/$1QRYSET.out
#           That file has 1 or more BIBID values in the form ('123','4342','1442')
# OUTPUT  : There are 33 columns for each result. 
#           Output will be saved in /tmp/ having name format $1-ITEMS.out
# PURPOSE : Collect all the holdings and or holdings with items for the
#	    bib records in the BIBID list. This is applicable to WRLC bibs.
# 
LOG=/var/www/wrlc/log/BIBID-$1.log
# remove list from previous processing of this bibid
echo "TIMER|"`date +%T`"|10searchitems" >> $LOG
echo "---------------------------------------" >> $LOG
echo '10searchitems:Item(s) that match bibset' >> $LOG
#
#
LD_LIBRARY_PATH=/usr/lib/oracle/10.2.0.4/client64/lib
export LD_LIBRARY_PATH
echo 'LD_LIBRARY_PATH:' $LD_LIBRARY_PATH
#
SQLPATH=/usr/lib/oracle/10.2.0.4/client64/bin/
export SQLPATH
echo 'SQLPATH:' $SQLPATH
#
$SQLPATH/sqlplus -S dbread/<PASSWORD>@'(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=<HOST>)(PORT=1521)))(CONNECT_DATA=(SID=VGER)))'<<EOF
set HEADING on
set ECHO off
set LINESIZE 10000
set PAGESIZE 2000
set COLSEP |
set WRAP off
set RECSEP off
set TERMOUT off
set FEEDBACK off
set SCAN off
set VERIFY off
set TRIMSPOOL on
spool /tmp/$1-ITEMS.out
SELECT 
LIBRARY.LIBRARY_NAME AS LIB, 
BIB_MFHD.BIB_ID, 
BIB_MFHD.MFHD_ID, 
MFHD_ITEM.ITEM_ID, 
ITEM_BARCODE.ITEM_BARCODE, 
LOCATION.LOCATION_CODE AS ITEM_PERM_CODE, 
'ITEM_PERM_LOC#' || ITEM.PERM_LOCATION AS ITEM_PERM_ID,
'ITEM_TEMP_LOC#' || ITEM.TEMP_LOCATION AS ITEM_TEMP_ID, 
'HOLD_LOC#' || MFHD_MASTER.LOCATION_ID AS MFHD_LOC_ID, 
ITEM_STATUS_TYPE.ITEM_STATUS_DESC,
BIB_MASTER.SUPPRESS_IN_OPAC AS BIBSUP, 
BIB_TEXT.ISBN, 
BIB_TEXT.ISSN, 
BIB_TEXT.LCCN, 
BIB_TEXT.NETWORK_NUMBER AS OCLC, 
MFHD_MASTER.SUPPRESS_IN_OPAC AS MFHDSUP, 
MFHD_MASTER.NORMALIZED_CALL_NO AS NORM_CALL, 
MFHD_MASTER.DISPLAY_CALL_NO AS DISP_CALL, 
LOWER(MFHD_ITEM.ITEM_ENUM), 
MFHD_ITEM.CHRON, 
'#MESSAGE#', 
BIB_TEXT.TITLE_BRIEF, 
BIB_TEXT.AUTHOR, 
BIB_TEXT.EDITION, 
BIB_TEXT.PUBLISHER, 
BIB_TEXT.PUB_PLACE, 
BIB_TEXT.PUBLISHER_DATE, 
BIB_TEXT.SERIES,
'NORMAL_VOL',
'#TITLEWRLC',
'#TITLEHOME',
'#VOLWRLC',
'#VOLHOME',
'#REQVAL'
FROM (((((((BIB_MASTER LEFT JOIN BIB_MFHD ON BIB_MASTER.BIB_ID = BIB_MFHD.BIB_ID) INNER JOIN BIB_TEXT ON BIB_MASTER.BIB_ID = BIB_TEXT.BIB_ID) INNER JOIN LIBRARY ON BIB_MASTER.LIBRARY_ID = LIBRARY.LIBRARY_ID) LEFT JOIN MFHD_MASTER ON BIB_MFHD.MFHD_ID = MFHD_MASTER.MFHD_ID) LEFT JOIN ((MFHD_ITEM LEFT JOIN ITEM ON MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID) LEFT JOIN ITEM_BARCODE ON ITEM.ITEM_ID = ITEM_BARCODE.ITEM_ID) ON MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID) LEFT JOIN LOCATION ON ITEM.PERM_LOCATION = LOCATION.LOCATION_ID) LEFT JOIN ITEM_STATUS ON ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID) LEFT JOIN ITEM_STATUS_TYPE ON ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE
WHERE BIB_MFHD.BIB_ID IN $2
ORDER BY LIB,NORM_CALL, ITEM_ENUM
/
spool off
EOF
